name: completed
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  adhan: null
  advance_pdf_viewer2: null
  animate_do: null
  audio_video_progress_bar: null
  auto_size_text: null
  awesome_dialog: ^3.2.0
  cached_network_image: ^3.3.1
  carousel_slider: null
  connectivity_plus: ^5.0.2
  country_calling_code_picker: ^2.0.1
  cupertino_icons: ^1.0.2
  dio: null
  equatable: null
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_screenutil: null
  flutter_staggered_animations: null
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: null
  fluttertoast: null
  font_awesome_flutter: null
  freezed_annotation: null
  gap: null
  geocoding: null
  geolocator: null
  get_it: null
  intl:
  json_annotation: null
  lottie: ^3.1.0
  macos_ui: null
  pin_code_fields: ^8.0.1
  responsive_framework: 0.2.0
  share_plus: null
  shared_preferences: null
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4
  page_transition: ^2.1.0
  dropdown_button2: ^2.3.9
  shimmer: ^2.0.0
  flutter_html: null
  syncfusion_flutter_datepicker: ^19.2.44
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  http_parser: null
  mime: null
  google_maps_flutter: ^2.2.8
  the_widget_marker: ^1.0.0
  flutter_polyline_points: ^2.0.0
  map_launcher: ^2.5.0+1
  animated_bottom_navigation_bar: ^1.3.3
  circular_reveal_animation: ^2.0.1
  video_player:
  chewie:
  youtube_player_flutter: ^9.0.1
  camera:
  google_sign_in: ^6.1.6
  flutter_facebook_auth:
  sign_in_with_apple:
  awesome_notifications:
  firebase_messaging:
  firebase_core:
  webview_flutter:

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/map_style.json

  fonts:
    - family: NeoSansArabic
      fonts:
        - asset: assets/fonts/NeoSansArabic.ttf